### ISSUE TITLE
Volume feedback on Loupedeck and screen stopped working

### ISSUE THREAD

**Issue by LQdbMusic** [shells-dw/loupedeck-totalmix#5]
Hi I don't know if this is driver related, but on M1/MacOs 13.3 I had to update the RME drivers to the beta ones v4.07 with TotalMix 1.80

After that, the refresh of the volume display settings stopped working, all other knobs (on Loupedeck device and on-screen)  seem to work as expected just fine. When I turn the volume knob RME display shows the new settings but TotalMix doesn't seem to "send out" the updated values to OSC devices.  

Any Idea what could cause this ?

**Comment by shells-dw** [comment]
Hi buddy,

dunno. I'm using 1.80 on Windows and there it's running fine with the Loupedeck.
On my Mac it's 1.78 and whatever latest driver release it comes with.
Maybe they changed something, it has a bug or something else is going on. I think 1.80 comes with more OSC values which shouldn't cause an issue (I took that into account and it works on Windows) but who knows...
I'll look into it tomorrow and keep you posted.

Thanks for reporting the issue <3

**Comment by shells-dw** [comment]
Well, installing that beta is 1 hour of my life I'm not getting back. Would be asked too much to make a proper installer or at least a proper uninstaller for the previous version that doesn't require 45 minutes of googleing and messing around with outdated information where files might be stored -maybe/possibly/depending- or f-ing with the system's security policy (which break everything else that also needs 3rd party extensions... sigh). Gotta love it.

Anyway, done ranting 😅 
Finally got v4.07 and TotalMix 1.80 running without breaking my system - and it works just fine on mic channels and physical out, but it does nothing on line or software channels for me.
Great.
It appears nothing is sent over OSC for those at all. Using a OSC reader thingy software doesn't show anything being sent by TotalMix for line and non-physical channels for volume, pan, phase, solo and line settings - only mute and gain seem to be sent (and for me also nothing is received there).

Not sure why you can control your faders (of line/software channels) still, that doesn't work for me either. I can't control anything except for Mute, Phase and Gain on those channels.

Looked at the corresponding OSC table, looks basically the same as it did before.

RME needs to fix that then, I can't use what's not available. Nothing I can do there sadly 🤷

**Comment by LQdbMusic** [comment]
Thanks for investing your time checking and finding out that RME messed up :-) Yeah quite frankly, reading the RME Forum posts about the Apple M1 quirks I really hope they can fix their multiple issues and of course I don't expect you to waste your time on broken beta drivers :-) Now we have a clear statement and I will contact RME support, letting them know they got a OSC issue there, thanks a ton !  

As I understood the RME guys, they blame Apple for not allowing them to access the HW-layer more directly anymore with new OS architecture. I have a bad feeling about RME and Apple M1 platform, but let's wait and see if they can maintain their high driver quality in the future esp. on MacOS.

**Comment by shells-dw** [comment]
Yeah no worries.
I mean I grew fond of criticising their software implementations during the years I've been developing this plugin, but here I guess it's fair enough... it's a beta release after all. I expect issues with that. That's what a beta is for in the end. Finding bugs. No clue how much they changed under the hood of 1.80 (or whatever causes the OSC issues) but apparently enough to have caused these issues - but as said, fair enough if it's fixed until they release it as final.

So far TotalMix at least ran reliable, leightweigt and well as long as I used it. Can't complain there. At least as long as you use it as intended and don't try to do too much with OSC :D
Since I moved to UAD years ago, I just have it installed for this plugin (and the Stream Deck version), other than that I don't use it at all anymore.

I don't know why they think they have to use DriverKit now, but I guess it makes it easier for ... some people. I don't think I know of any Mac that's used for audio that doesn't have its security policy set to allow 3rd party extensions as _a lot_ of stuff needs that, but heyho. I guess it's good not to cling to old things. Or whatever. Sure, Apple restricts their platform more and more, which has advantages and surely disadvantages. I don't know about any deadline or statement that would ban 3rd party extensions though. Wouldn't be a great move, I have probably 6 different hardware components that still use that approach.
Would just have been nice if they either set up their installer in a way that properly removes the old version or provide a seperate uninstaller for the extension based version with it. This (slightly overexaggerated) "_well just figure it out yourself, we don't care if you don't want to set the security policy to default and f up all your hardware from other companies with it"_ approach that's promoted in the forums is questionable in my personal opinion. Then again, I don't like the tone in their forums very much anyway, which is why I stopped being active there years and years ago.

Anyway, good luck - let me know when they fixed it or gave you feedback

Cheers
