### ISSUE TITLE
8 channels limitation

### ISSUE THREAD

**Issue by ChrApww** [shells-dw/loupedeck-totalmix#7]
Hello Dominik, I hope you're having a very good Xmas time.
I've just found your plugin that looks to be very promising, but I understand that because you own a Fireface UC, you haven't pushed the possibilities to their maximum.

For example: I can list only 8 channels for each action (whether a button or a dial), but as I own a FF UFX, I need to manage 30 IOs : 12 analog+1 AES+2x8 Adat, and the dsp functions such as EQ, Dynamics, and FXs. But new devices are including way more IOs like Madi, Dante and so on.
Of course, TMFx offers the possibility to arrange all IOs in various configs, so I'm aware that any OSC remote controller would comply with that visualization for channel identifications.

I don't know anything about programming plugins like you did as specified by Loupedeck, but I thought I may find in the code if there's a fixed limit for channel counting. But apparently, it should be gathered from the unit, if I'm well understanding this :
// create channels as per how many channels were detecte
            for (var i = 1; i < Globals.channelCount+1; i++)

So I should see as many channels as displayed in my RMFx arrangement right ?
=> as it happens, I can only see 8 channels, but I cant' figure out which one they address in my panel
![Capture d’écran 2023-12-29 à 23 57 56](https://github.com/shells-dw/loupedeck-totalmix/assets/120128405/7fb87185-f355-4c71-906d-1d725e1cffa1)

For your information in the picture, I have opened all possible parameters' tabs in various channels :
- top row : the mic main settings
- bottom row : the output main settings, the EQ settings and the Dynamics settings
- right side : the 2 FX tabs
I guess you're fuly aware of the excel file that compiles all possible OSC commands for RME, but you'll find it here if necessary : https://docs.google.com/spreadsheets/d/1F1tDlnBOg2axFm1DaW8fEyssuFK79WvwPsiSqwpwqUo/edit?usp=drive_link

I'm now quite trained to the Loupedeck workspace & profiles settings, as I've got the full monty with a CT. I'm very happy to use it into Reaper and have set some profiles to control advanded plugins with Midi strings.
![Capture d’écran 2023-12-30 à 00 13 56](https://github.com/shells-dw/loupedeck-totalmix/assets/120128405/d672d0bc-a1fb-4887-b313-bfc15815ba86)

So I'd be very happy to help in your developments, although I know you've not been working on it for a while...
All the best - Chris

**Comment by ChrApww** [comment]
Progressing into setting up the CT with your plugin, I've found a problem :
- Loupedeck doesn't know the difference between an input, playback or output channel when it comes to assign an action if it's defined on the same channel than another one
![Capture d’écran 2023-12-30 à 11 54 38](https://github.com/shells-dw/loupedeck-totalmix/assets/120128405/7641c08c-07d3-424e-b920-06628abf062a)

=> then I get this message :
![Capture d’écran 2023-12-30 à 11 58 20](https://github.com/shells-dw/loupedeck-totalmix/assets/120128405/10336f06-9687-41f2-9ca8-7528264f23f6)

**Comment by shells-dw** [comment]
Hi Chris,
happy New Year :)

It should handle more than 8 channels, if you [set it up correctly](https://github.com/shells-dw/loupedeck-totalmix#setup-for-osc). Particularly the fader count in the OSC setup. If you set that to however many channels you have, it should work with them. Not sure why that defaults to 8 channels no matter what device you have, but I guess it's at least consistent to the overall OSC implementation on Firefaces.
In the boundaries of the limitations RME brings with their implementation (mostly Stereo-Channels collapsing channel list, e.g. if you have channels 1-8 set to mono, channel 4 will be channel 4, but if you stereo'd 1+2 then channel 4 becomes channel 3 and so on).

I'll look into more if you confirm you indeed set the OSC setup correctly and it still doesn't work.

Cheers

**Comment by ChrApww** [comment]
Hi Dominik, thanks for your reply.
I've been digging deeper into OSC and RME implementation, but I haven't found a "variable" in the plugin setup that looks to be related with the channel count other than the one mentioned in my 1st post...

Here's my config panel that complies with your specs : hoowever, changing the "number of faders per bank" dont do anything if it's the parameter you're thinkinhg about ...?
![Capture d’écran 2024-01-02 à 13 20 19](https://github.com/shells-dw/loupedeck-totalmix/assets/120128405/8207c30d-970f-40ba-8586-2c951eb9e977)

The way RME arrange the TMFx channels actually depends on this panel, where you can "hide" channels in different "domains" : so this channel X may be apparent in the main screen but untouchable by whether Midi or OSC layer(s) :
![Capture d’écran 2024-01-02 à 12 46 07](https://github.com/shells-dw/loupedeck-totalmix/assets/120128405/27f976df-41a7-436f-a9f1-0c06147dc2b0)

So far here are my conclusion :

- one important parameter is really missing : Master Mute !
- in order to assign the CT knobs & switches to all the parameters available, it'd be very nice to implement all OSC tsrings described in the G-Sheet linked in y 1st post, and at least the ones that allows to navigate across channems and rows, so that selecting a single channels would be quick and easy ;-) !

Thanks a lot for your understanding and the time dedicated to this plugin, I wouldn't hesitate to dedicate a "budget" to make it happen as soon as possible, if it's a good motivation...

All the best, Chris

**Comment by shells-dw** [comment]
Hi Chris,

yeah, that was "Numbers of faders per bank" was what I was thinking about.

So... just to be sure I understand the issue correctly - you set that to 24 and restarted the Loupedeck software to be sure afterwards (I can't remember if that would be updated on the fly right now, I didn't really use the Loupedeck too much honestly) and it doesn't offer you 24 channels in the channel selection in my plugin then?
Or does it offer the 24 channels but actions don't trigger the right channel?
Whatever you set "Numbers of faders per bank" to, my plugin should reflect that and offer this amount of channels to control. If it's set to 8 (which is the default of TotalMix) or you didn't restart the Loupedeck software after making the change, that would be the most obvious explanation why it would only show 8 channels. I had someone test that on his UFX II a year ago or so when I released it and it worked for him. Since I haven't touched anything since then I would assume it still does if setup correctly.

This numbers of faders per bank setting is independend of anything you set somewhere else and controls only the OSC server of TotalMix. if this is set to 8 you can control channels 1-8 on either bank (input, playbacks, outputs) using OSC, regardless how many you have or how you've routed or combined them. If you set that to 24, you can obviously control 24 channels per bank, regardless if your device even offers so many channels or if you "hid" them from OSC using the Channel Layout page. This just controls how many channels are adressable using OSC and OSC only - and thus my plugin, if this is set to 8, will only show 8 channels as only 8 channels can be controlled using OSC in that case. If you combine  24 channels (for example) in Stereo and use them exclusively in Stereo, you are fine with 12 channels as there are only 12 to control. This will make the plugin more responsive as less data has to be processed and as TotalMix combines Stereo tracks into one track, this doesn't matter anyway.

For the plugin (or anything connected to OSC) it's sadly rather hard to tell what's going on generally, as described above, if you combine two channels (say channel 1 and 2) to a Stereo pair, it's not like that you control that pair using channels 1 and 2 or channel 1 and channel 2 would become unresponsive or whatever they could've done - but at that very moment, it combines channels 1 and 2 in channel 1 and channel 3 becomes channel 2. This is somewhat hard to catch, I'm already querying TotalMix as much as sensible with the CPU load that causes. Despite that I wouldn't know what to do with that information, when you set a button to trigger something on channel 2 I do not know if you actually want to control the former mono channel 2 or the now shifted down channel 3, hence automating that is ... well, probably just not worth it. If I have it switch down to 1 then, you have 2 buttons controlling channel 1 which causes confusion, if I leave it, and you didn't want to control channel "3" but it does, confusion as well. I didn't figure something out that wouldn't be a not-optimal solution.
Hope that all makes sense 😅 

Regarding the second screenshot - by default all channels are mapped. If you change that, you have to adapt to that somehow on your own. As this is fully flexible I don't really know how to handle this better in the plugin. it's not like the OSC implementation is user friendly. As far as I know, this is nothing I could query from TotalMix, so I don't have a clue that channel 3 might actually be channel 10 when 3-9 are hidden from OSC, there is just no way. It will be addressed as channel 3 in OSC then. I wouldn't know it's actually channel 10 as it's (staying in this example) the 3rd channel that is controlable. If you run such a setup, I guess you have to adapt to it yourself.

 Global Mute is implemented. Master Mute works too, but the Master Fader is ... I think the last fader of the outputs, it's 16 for my interface, but I think you have to figure that out yourself which it is on yours, I bet it's 24 if you set it to 24, but... who knows.
Thing is that this is handled like a normal channel more or less. I have Global Mute implemented which, well, triggers Global Mute, but muting only the Master Channel will include you figuring out which this channel is for your interface, then you can trigger it with a normal Channel Mute.

Yeah, I'm not sure if I'll be adding functionality to this plugin going forward. I don't use the Loupedeck at all and switched to UAD years ago, so my UC is collecting dust and used probably once a year for anything else than developing this or the StreamDeck plugin... sooooo yeah, I don't think I'll do much to it.
Planning on updating the StreamDeck version to support SD+ in the near future (maybe, probably), but developing for Loupedeck is a bit of a mess and I don't really have enough spare and free time to code stuff for platforms I don't use anymore for hardware I don't use anymore for the sole purpose to gift it all away on the internet. So yeah, code is open source/MIT, feel free to code whatever you can/like, but other than giving support and probably fixing issues caused by platform updates (either by Loupedeck or RME) I won't add features.

Cheers anyway, hope that helps you :)

**Comment by ChrApww** [comment]
Dear Dominik, thanks for this comprehensive reply.
I do understand you won't do much to the plugin anymore, so I'll be trying to find someone fluent with C# to restart from your source... However to answer your questions :

`So... just to be sure I understand the issue correctly - you set that to 24 and restarted the Loupedeck software to be sure afterwards (I can't remember if that would be updated on the fly right now, I didn't really use the Loupedeck too much honestly) and it doesn't offer you 24 channels in the channel selection in my plugin then?
Or does it offer the 24 channels but actions don't trigger the right channel?`

=> Yes, I've tried as many restart and refresh actions as I could, but no, it's the list of available channels that remains stuck at 8.

`For the plugin (or anything connected to OSC) it's sadly rather hard to tell... `

=> yep, I've well understood how the entire TMFx is managed by various panels, more or less independant from each others, so that render what's going on erratic somehow. But, I've set quite a fixed configuration that I never change, so it's easier to assign controls and keep them consistent.

`Global Mute is implemented. Master Mute works too, but the Master Fader is ... I think the last fader of the outputs, it's 16 for my interface, but I think you have to figure that out yourself which it is on yours, I bet it's 24 if you set it to 24, but... who knows.
Thing is that this is handled like a normal channel more or less. I have Global Mute implemented which, well, triggers Global Mute, but muting only the Master Channel will include you figuring out which this channel is for your interface, then you can trigger it with a normal Channel Mute.`

=> there's actually a big difference between "global" and "master" : the global functions are "authorizations" to activate mute, solo and free modes, or more practically to forbid these actions that could impact severely a recording session for example.
The Master group is an assignment for the parameters stiing at the right of the panel, and work for any physical output which is assigned to the Master Track (the AES out in my case). Also, my version can handle up to 4 specific headphone channels, that I can address with the Talkback function. But, in the XL file, there's no such string as a "Master Mute", so I guess I'll do your way by assigning a simple mute action to the related channel...

`Yeah, I'm not sure if I'll be adding functionality to this plugin going forward. I don't use the Loupedeck at all and switched to UAD years ago, so my UC is collecting dust and used probably once a year for anything else than developing this or the StreamDeck plugin... sooooo yeah, I don't think I'll do much to it.`

=> I do understand your point very well.
However, I've paid a visit to the code although I know very little about programming, and I have noticed that any given "parameter" listed in the XL file has to just be "declared" in each of the 3 sections' file (in, PB & out) in respect with whether they are a switch (triggers) or a knob (adjustments), right ?
What if I just duplicate things that compare 1 to 1 and change the related string name ?
...or is it more complicated than that and I'd rather hire a programmer fluent in C# ?

Things are : what you've done is already fantastic, and I'm just missing a small final step...
It'd be grateful from you to make it happen 👍 👍 👍

**Comment by shells-dw** [comment]
> 
> `So... just to be sure I understand the issue correctly - you set that to 24 and restarted the Loupedeck software to be sure afterwards (I can't remember if that would be updated on the fly right now, I didn't really use the Loupedeck too much honestly) and it doesn't offer you 24 channels in the channel selection in my plugin then? Or does it offer the 24 channels but actions don't trigger the right channel?`
> 
> => Yes, I've tried as many restart and refresh actions as I could, but no, it's the list of available channels that remains stuck at 8.

Hm. I'll have to look into that. It should work like that. Then it's, for whatever reason, not really detecting all the available channels. Which is strange as I try to deduct that from the device response, so for whatever reason it doesn't seem to be able to parse that correctly. I see you're using it on MacOS, maybe it has something to do with that. Well, when I get time to look into the StreamDeck update I'll look for my Loupedeck and hook it up too, see if I can find something out. Seems like a bug or something caused by any software update since I released it. I'm sure it worked, also on MacOS.
So just to be sure, you changed it to 24 for both OSC servers ("remote controllers", right?

>
> `Global Mute is implemented. Master Mute works too, but the Master Fader is ... I think the last fader of the outputs, it's 16 for my interface, but I think you have to figure that out yourself which it is on yours, I bet it's 24 if you set it to 24, but... who knows. Thing is that this is handled like a normal channel more or less. I have Global Mute implemented which, well, triggers Global Mute, but muting only the Master Channel will include you figuring out which this channel is for your interface, then you can trigger it with a normal Channel Mute.`
> 
> => there's actually a big difference between "global" and "master" : the global functions are "authorizations" to activate mute, solo and free modes, or more practically to forbid these actions that could impact severely a recording session for example. The Master group is an assignment for the parameters stiing at the right of the panel, and work for any physical output which is assigned to the Master Track (the AES out in my case). Also, my version can handle up to 4 specific headphone channels, that I can address with the Talkback function. But, in the XL file, there's no such string as a "Master Mute", so I guess I'll do your way by assigning a simple mute action to the related channel...

I know. But the problem is, that the Master and headphone channels are not directly adressable over OSC as far as I'm aware (and this is from memory too, I didn't look into it for nearly a year - so my memory may betray me here, however since you weren't able to find them their spec sheet either, I'm rather sure I'm correct here). They are just additional channels behind your other output channels. It's dynamic depending on how many channels you have before that, I think at least. As I only have my UC to test with, I know it's somewhere behind the physical outputs, but on devices with 30 channels and 4 headphone channels even if they are not custom configured I can only assume it's different. So I can't tell it "TotalMix, Mute master" or "mute headphone 3" and it knows what to do, (as I can with Global Mute for example) I have to tell it "mute channel x" and that means I'd need to know which channel that is, but as the channels are dynamic and TotalMix (or at least its OSC implementation) treats that simply as any other channel, I can't really know which channel that will be on. Hence you'll have to figure that out by try and error for your setup (start on the last output channel and work downwards - however that will probably be an issue if you only see 8 channels) and if your setup is rather static that should be fine. I really don't know how I would be able to do that at all, this is not even about time, I'd love to know it for the StreamDeck too ;) I looked into it a bunch over the years but didn't find a reliable way to do that.

> 
> `Yeah, I'm not sure if I'll be adding functionality to this plugin going forward. I don't use the Loupedeck at all and switched to UAD years ago, so my UC is collecting dust and used probably once a year for anything else than developing this or the StreamDeck plugin... sooooo yeah, I don't think I'll do much to it.`
> 
> => I do understand your point very well. However, I've paid a visit to the code although I know very little about programming, and I have noticed that any given "parameter" listed in the XL file has to just be "declared" in each of the 3 sections' file (in, PB & out) in respect with whether they are a switch (triggers) or a knob (adjustments), right ? What if I just duplicate things that compare 1 to 1 and change the related string name ? ...or is it more complicated than that and I'd rather hire a programmer fluent in C# ?

possibly, but my experience with TotalMix and OSC is generally, that nothing is as easy as it looks in the first place ;) Some things are, but some aren't.
If you feel up for it, just give it a try I would say. For most features I didn't implement I have no way of testing them anyway, so it's kind of tricky for me to put something in without any way to test it - and later debug it, if people complain about them not working. It's time-consuming enough reverse engineering half of that OSC setup of RME without having to cook versions, ship them to a user, query feedback that might or might not be filtered and misleading and then do it all again, despite finding someone willing to do that. I'm not really into spending another 2 weekends on this.
TotalMix responds to queries even if the device doesn't support them (like toggleing on FX or some stuff like that my UC doesn't have), but these are not necessarily very helpful, or a positive response doesn't necessarily mean it's working with a real device.

> 
> Things are : what you've done is already fantastic, and I'm just missing a small final step... It'd be grateful from you to make it happen 👍 👍 👍

Thanks, happy it's helpful :)

**Comment by ChrApww** [comment]
`So just to be sure, you changed it to 24 for both OSC servers ("remote controllers", right?`
=> I think I've tried all possible numbering combinations, but always the same on both OSC 1 & 2 layers...

For the rest of your sayings, I get all the points, and especially the importance of having everything at hands when adding lines, being able to test new codes right away. I'm sure there must be some guy at ease with C# in my surrounding, the question is how long does it take to make it as I'd like ? If I hear you, it's a couple of weekend, something like 8-10 hours right ? Do you think any other langage knowledge would be ok, like C; C++, Python or Java ?

About the fader numbers, the Loupedeck configurator is at the V5.8.1 and the TMFx at 1.85 ...along with Monterey OS, it could just be these changes that have make that variable unrespsonsive.

**Comment by shells-dw** [comment]
> `So just to be sure, you changed it to 24 for both OSC servers ("remote controllers", right?` => I think I've tried all possible numbering combinations, but always the same on both OSC 1 & 2 layers...

hm, I'll have to look into that then.

> 
> For the rest of your sayings, I get all the points, and especially the importance of having everything at hands when adding lines, being able to test new codes right away. I'm sure there must be some guy at ease with C# in my surrounding, the question is how long does it take to make it as I'd like ? If I hear you, it's a couple of weekend, something like 8-10 hours right ? Do you think any other langage knowledge would be ok, like C; C++, Python or Java ?

Based on my experience working with TotalMix and OSC I wouldn't say it's mostly an issue of deep programming skills or the language used, the difficulties come from dealing with TotalMix over OSC. I would say I spent around 70-80% of the time on these plugins overall on finding ways around the limitations of that. It just is a bloody mess, as some things are global, others are directly addressable and for others you need to be on the right bank (Input, Playback or Output) to control the right channel and dynamic things like this disappearing of channels when you combine them to Stereo, some values use proper floats, others are triggered on _and_ off by sendind 1.0f, others are just toggled on when doing that and they require 0.0f to be switched off and everything above 0.0f is toggling on - is just added fun on top.
So to answer your question more specifically: I don't have a clue how long I'd need, so I could only guess how long someone else who's not familiar with that might be needing. Plus I can only recommend using a real interface with TotalMix, because, as mentioned above, despite its responding to commands that the device does not support, it might actually not work as you intent after all when connecting a real device, at least that was the experience for me when I tried to do that to add functions mine doesn't supporrt. Maybe it's done in an hour, maybe it turns out to not be reasonably possible after spending 10h on it because TotalMix just does its thing. The fact that TotalMix needs to be actively queried and doesn't send out events is rather heavy on the CPU, I've added more functionality that would be able to detect changes like stereo-ing channels and stuff but that made the plugin a lot slower and/or put more load on the CPU, so I threw it out again. So, long story short, can't tell how long someone not familiar with TotalMix and its OSC implementation would need, not a clue. Maybe 1h maybe 20, maybe it turns out not to be feasible at all doing that.

**Comment by ChrApww** [comment]
Hi Dominik, thanks a lot for your comments.
Fact is that your plugin do not connect to TMFx anymore, since yesterday night ! 👎 
![Capture d’écran 2024-01-03 à 11 45 51](https://github.com/shells-dw/loupedeck-totalmix/assets/120128405/f39773f9-1dfd-4954-b16b-15715c7f3ba1)

I don't know what happened, maybe it's playing with the fader numbers ...?
Of course I've double, triple checked the RME settings...

I've uninstalled & reinstalled all : Loupedeck driver, your plugin, and currently looking at RME updates.

But to my big surprise, it happens that updating TMFX 1.83 to 1.85 actually ends in the 1.83 version !?!
It looks that they're messing up with the M series in Mac, so there's a lot of confusion of what's to be done in order to be up to date with my config...
I'll be back to you as soon as soon as I can make your plugin working again, otherwise I don't tthink I'll go further into it...

**Comment by shells-dw** [comment]
I think if changing stuff would break things, that broke 1h into development. This message means it isn't able to connect to the OSC server of TotalMix. I've had that a couple of times, toggling "Enable OSC control" off and on again and/or removing both OSC Controllers from "Submix linked to OSC Controller" and adding them again always fixed it. Seems like a bug in TotalMix (or it's intended, since I have had this for various versions).
  
 I developed it on an M-series Mac, so that shouldn't be it, but I have v1.80 installed. Tried the 1.83beta but that caused some issues (before even trying to use OSC) on my device so I went back to the most recent version at the time, which was 1.80 apparently.

_edit: rewording for clarity_

**Comment by ChrApww** [comment]
tried many things, including all OSC tweaks... In Loupedeck, how do you know if you've "reset" the plugin ?

**Comment by shells-dw** [comment]
Not sure. Loupedeck is a bit strange, but uninstalling it and getting rid of /Users/USERNAME/.local/share/Loupedeck/PluginData/TotalMix should do the trick. Check if there's a folder called TotalMix left in Plugins (instead of PluginData) after uninstalling, delete that too, then reinstall. Otherwise no clue

**Comment by ChrApww** [comment]
I found this too
![Capture d’écran 2024-01-03 à 17 38 44](https://github.com/shells-dw/loupedeck-totalmix/assets/120128405/7aaa3a58-6656-495a-8c4f-fa752cd18c48)

**Comment by ChrApww** [comment]
as well as this one
![Capture d’écran 2024-01-03 à 17 43 21](https://github.com/shells-dw/loupedeck-totalmix/assets/120128405/d9891fc3-c3a9-429b-b93e-d5b8f83baa37)

**Comment by ChrApww** [comment]
Hi Dominik, whatever I've tried had given no positive result, the plugin won't connect to TMFx anymore.
Despite trashing everything I found, re-installing all softwares implicated, thorough reviews of all parameters, I'm obliged to give up on this plugin that wonderfully worked at the beginning !!

The more I dig in the very limited RME documentation & info about how they manage OSC, the more I'm inclined to think TMFx is poorly designed in this aspect 👎 ...I guess it's more profitable for them to sell the ARC.
I think you've done your best to make it happen, and I thank you so much for all the support you've given.
I wish you the best 2024 you may hope !

**Comment by ChrApww** [comment]
Hi Dominik, I was so frustrated

- looked into the "TotalMix.log" and read : "2024-01-02T18-30-38-4425 |  11 | ERROR | 1/2/2024 6:30:38 PM - TotalMix: CheckForTotalMix() -> totalMixAvailable = false"
- in the file "settings.json", I've turned  "skipChecks" to "true", and boom ! all my troubles gone 👍 

=> not only can I connect, but I've overcome the 8 channels limitation
=> new trouble : now displaying the value returned from a dial action is lagging a lot
So it's a real progress ;-)

{
  "host": "127.0.0.1",
  "port": "7001",
  "sendPort": "9001",
  "backgroundPort": "7002",
  "backgroundSendPort": "9002",
  "mirroringEnabled": "true",
  "skipChecks": "true",
  "enableLogging": ""
}
